#!/bin/bash
# MAS
# Multiplexer Adminstrator Solution
# Configuration file
# License: GPL v2 or later
# Author: Aurelien DESBRIERES - aurelien@hackers.camp


############################### Works Fine #####################################
#                                                                              #
# for dnf / yum / pacman / apt                                                 #
# search / install / update / upgrade or parsing argument                      #
#                                                                              #
# mussh -a -i /home/$the_user/.ssh/$private -d -H mas-hostfile -c 'date' -m2   #
# mussh -a -i ~/.ssh/id_rsa -d -H mas-hostfile -c 'bash MAS/update.sh' -m2     #
# find a way to authenticate yourself as root non-interactively                #
#                                                                              #
################################################################################

mas() {

tput clear

printf "\033[1;32mWelcome to MAS - Multiplexer Adminstrator Solution\033[0m\n"
printf "\033[1;32mMAS offer you the way to works with different OS type like they were all the same\033[0m\n"

printf "\033[1;32mPlease report your needs to:\033[0m aurelien@hackers.camp\n"
printf "\033[1;32mYou need root privileges to run it\033[0m\n"

# request the user what he want to do
# execute the file in git during the configuration on the machine
while true; do
    echo "What do you want to do?"
    read -p "Update & Upgrade or Search or Install? " usi
    case $usi in
	[Uu]* ) cd /home/$the_user/MAS-REPORT/
		mussh -a -i /home/$the_user/.ssh/$private -d -H mas-hostfile -C 'update.sh' -m2
		break;;
	[Ss]* ) echo "which software are you looking for? "
	        read soft_search
      		cp search.sh /home/$the_user/MAS-REPORT/
	        cd /home/$the_user/MAS-REPORT/
		sed -i "s/soft_search/$soft_search/g" search.sh
		chmod +x search.sh
		echo "Loading MAS search please wait "
		mussh -a -i /home/$the_user/.ssh/$private -d -H mas-hostfile -C 'search.sh' -m2
		break;;
	[Ii]* ) echo "which software do you wish to install? "
		read soft_install
		cp install.sh /home/$the_user/MAS-REPORT/
		cd /home/$the_user/MAS-REPORT/
		sed -i "s/soft_install/$soft_install/g" install.sh
		chmod +x install.sh
		echo "Loading MAS install please wait "
		mussh -a -i /home/$the_user/.ssh/$private -d -H mas-hostfile -C 'install.sh' -m2
		break;;
	* ) echo "Please answer 'U'pdate/'U'pgrade or 'S'earch or 'I'nstall.";;
    esac
done



}
