#!/bin/bash
# MAS
# Multiplexer Adminstrator Solution
# Configuration file
# License: GPL v2 or later
# Author: Aurelien DESBRIERES - aurelien@hackers.camp


############################### Works Fine #####################################
#                                                                              #
# for dnf / yum / pacman / apt                                                 #
# search / install / update / upgrade                                          #
#                                                                              #
# mussh -a -i /home/$the_user/.ssh/$private -d -H mas-hostfile -c 'date' -m2   #
#                                                                              #
################################################################################

mas() {

#tput clear

printf "\033[1;32mWelcome to MAS - Multiplexer Adminstrator Solution\033[0m\n"
printf "\033[1;32mMAS offer you the way to works with different OS type like they were all the same\033[0m\n"

printf "\033[1;32mPlease report your needs to:\033[0m aurelien@hackers.camp\n"
printf "\033[1;32mYou need root privileges to run it\033[0m\n"

# request the user what he want to do
# execute the file in git during the configuration on the machine
while true; do
    echo "What do you want to do?"
    read -p "Update & Upgrade / Search / Install? " usi
    case $usi in
	[Uu]* ) mussh -t -a -i /home/$the_user/.ssh/$private -d -H mas-hostfile -c '~/MAS/update.sh' -m2 ; break;;
	#[Uu]* ) . test-update ; test-update ; break;;
	#[Ss]* ) . search ; search ; break;;
	#[Ii]* ) . install ; install ; break;;
	* ) echo "Please answer 'U'pdate or 'S'earch or 'I'nstall.";;
    esac
done

}
